sudo: false
dist: xenial
language: python
env:
  global:
  - PIP_RETRIES=10
  - PIP_TIMEOUT=30
  - BROWSER=firefox
  - GECKODRIVER=0.24.0
  - MOZ_HEADLESS=1
matrix:
  include:
    - python: 3.7
      env: TOXENV=checkqa
    - python: 3.5
      env: TOXENV=base-py35-django20-sqlite
    - python: 3.6
      env: TOXENV=base-py36-django21-sqlite
  allow_failures:
  - env: TOXENV=base-py35-django20-sqlite
  - env: TOXENV=base-py36-django21-sqlite
install:
- travis_retry pip install -U pip
- travis_retry pip install tox
- travis_retry pip freeze
services:
  - firefox: latest
before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER/geckodriver-v$GECKODRIVER-linux64.tar.gz
  - mkdir -p geckodriver && tar -xzf geckodriver-v$GECKODRIVER-linux64.tar.gz -C geckodriver
  - export PATH=$(pwd)/geckodriver:$PATH
before_script:
- if echo "$TOXENV" | grep mysql; then mysql -e 'create database autocomplete_light_test;';
  fi
- if echo "$TOXENV" | grep postgresql; then psql -c 'create database autocomplete_light_test;'
  -U postgres; fi
script:
- tox -r
- test -d .tox/$TOXENV/log && cat .tox/$TOXENV/log/*.log || true
after_success:
- travis_retry pip install codecov
- cd test_project && codecov
notifications:
  irc:
    channels:
    - irc.freenode.org#yourlabs
    template:
    - "%{repository} (%{commit} %{author}) : %{message} %{build_url} %{compare_url}"
cache:
  directories:
  - .tox/$TOXENV
  - $HOME/.cache/pip
deploy:
  provider: openshift
  user: jpic@yourlabs.org
  password:
    secure: FuIzy9CJ1+SSsLFVXj942Y4DYzv2NLAktHML+VB3IBR+JdJ4cTW7lftwUmmghXE4HmBoHbKsDlpwN/dErPy0yDl2bv3ejJWRWyekIOyu0Omwia0PDTEt6n/mryrQ92dAyjpD6SeypotHqhOCnj1HxJdgwL4EmzG+5o9n8eNte0M=
  app: dal
  domain: yourlabs
  deployment_branch: master
  skip_cleanup: true
  on:
    repo: yourlabs/django-autocomplete-light
    branch: master
